apiVersion: v1
kind: Template
labels:
  template: firehose-fetcher
metadata:
  name: firehose-fetcher
  annotations:
    description: firehose-fetcher
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: firehose-fetcher
    name: firehose-fetcher
  spec:
    replicas: 1
    selector:
      service: firehose-fetcher
    template:
      metadata:
        labels:
          service: firehose-fetcher
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: WORKER_ADMINISTRATION_REGION
            value: "api"
          - name: FIREHOSE_STREAM_URL
            value: ${FIREHOSE_STREAM_URL}
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
               name: aws
               key: s3-access-key-id
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-secret-access-key
          - name: BAYESIAN_SYNC_S3
            valueFrom:
              secretKeyRef:
                name: aws
                key: sync-s3
          # this won't get used if running with SQS
          - name: RABBITMQ_SERVICE_SERVICE_HOST
            value: bayesian-broker
          - name: PGBOUNCER_SERVICE_HOST
            value: bayesian-pgbouncer
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: firehose-fetcher
          livenessProbe:
            exec:
              command:
              - cli
              - "--liveness"
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - cli
              - "--liveness"
            initialDelaySeconds: 15
            timeoutSeconds: 1
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1024Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: firehose-fetcher
    name: firehose-fetcher
  spec:
    selector:
      service: firehose-fetcher

parameters:
- description: URL where libraries.io Firehose stream is running
  displayName: Firehose Stream URL
  required: true
  name: FIREHOSE_STREAM_URL
  value: "http://firehose.libraries.io/events"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-analytics/firehose-fetcher"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag